# Generated by Django 4.0.6 on 2022-07-11 23:51

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Produtos',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('nomeProduto', models.CharField(max_length=50)),
                ('especificacoesProduto', models.CharField(max_length=120)),
                ('corProduto', models.CharField(max_length=10)),
                ('preco', models.FloatField(default=0.0)),
            ],
        ),
        migrations.CreateModel(
            name='Modelos',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('modeloDescricao', models.CharField(max_length=30)),
                ('modeloProduto', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='core.produtos')),
            ],
        ),
        migrations.CreateModel(
            name='CategoriaProduto',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('descricaoCategoria', models.CharField(max_length=60)),
                ('produtoCategoria', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='core.produtos')),
            ],
        ),
    ]
