# Generated by Django 4.0.6 on 2022-07-12 00:02

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0001_initial'),
    ]

    operations = [
        migrations.RenameModel(
            old_name='Modelos',
            new_name='Modelo',
        ),
        migrations.RenameModel(
            old_name='Produtos',
            new_name='Produto',
        ),
    ]
